CREATE TABLE `practice`.`practice_double_ball`
(
`id` INT(10) NULL DEFAULT '0' COMMENT '期数' ,
`red1` SMALLINT(3) NOT NULL DEFAULT '0' COMMENT '红球1' ,
`red2` SMALLINT(3) NOT NULL DEFAULT '0' COMMENT '红球2' ,
`red3` SMALLINT(3) NOT NULL DEFAULT '0' COMMENT '红球3' ,
`red4` SMALLINT(3) NOT NULL DEFAULT '0' COMMENT '红球4' ,
`red5` SMALLINT(3) NOT NULL DEFAULT '0' COMMENT '红球5' ,
`red6` SMALLINT(3) NOT NULL DEFAULT '0' COMMENT '红球6' ,
`blue` SMALLINT(3) NOT NULL DEFAULT '0' COMMENT '篮球' ,
`winner` SMALLINT(3) NOT NULL DEFAULT '0' COMMENT '中奖人数' ,
`sale` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '销售额' ,
`jackpot` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '奖池金额' ,
`detailpage` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '详情页地址' ,
`date` INT(10) NOT NULL DEFAULT '0' COMMENT '开奖日期YYYYmmdd' ,
UNIQUE `id` (`id`)
)ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = '双色球开奖信息';